# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aman Bhatta
description: >-
  Personal webpage of Aman Bhatta. CSE PhD Student at the University of Notre Dame. 
  Research interests in deep learning, computer vision, long-range video understanding 
  and generation, and fairness in AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhatta1234.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "abhatta1234/abhatta1234.github.io"

# Author information
author:
  name: "Aman Bhatta"
  avatar: "/images/ab.jpeg" # path to your avatar image, e.g., /assets/images/bio-photo.jpg
  bio: "CSE PhD Student, University of Notre Dame"
  location: "South Bend, IN"
  email: "abhatta@nd.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amanbhatta"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhatta1234"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap" # or "ai ai-google-scholar" if using academicons
      url: "https://scholar.google.com/citations?user=kNwnZwsAAAAJ&hl=en"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/yourusername"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Using remote theme
# theme: minimal-mistakes-jekyll # Alternative: use if you have the gem installed locally

# Minimal Mistakes Theme settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: False # Enable search

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show per page
paginate_path: /page:num/

include:
  - _pages
  - images # Make sure your images folder is included

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously handled by Gemfile group :jekyll_plugins)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Defaults for collections
defaults:
  # _pages
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  # _posts
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      show_date: true
      read_time: true
      comments: false # Set to true to enable comments if configured
      share: true
  # _publications (new collection)
  - scope:
      path: "" # an empty string here means all files in the project
      type: "publications"
    values:
      layout: "archive"
      author_profile: false # Can be true if you want author profile on publication items
      show_date: true

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/
