# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Aman Bhatta"
name                     : "Aman Bhatta"
description              : "Personal webpage of Aman Bhatta, CSE PhD Student at the University of Notre Dame. Research interests in deep learning, computer vision, long-range video understanding and generation, and fairness in AI."
url                      : https://abhatta1234.github.io
baseurl                  : ""
repository               : "abhatta1234/abhatta1234.github.io"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
comments:
  provider               : false
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Aman Bhatta"
  avatar           : "ab.jpeg" # Ensure this image is in your images/ directory or root
  bio              : "CSE PhD Student, University of Notre Dame"
  location         : "South Bend, IN"
  employer         : "University of Notre Dame"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=kNwnZwsAAAAJ&hl=en"
  email            : "abhatta@nd.edu"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "abhatta1234"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : "amanbhatta"
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache/
  - node_modules/
  - tmp
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\\n\\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji

# HTML Compression
# Minify HTML output by default
# HTML_COMPRESSION:
#   enabled: true
#   ignore:
#     envs: ['development'] # don't minfy during development build

# Default Front Matter
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default # A default layout, assuming you might create one later
      author_profile: true
  # _publications
  - scope:
      path: "_publications"
      type: publications
    values:
      layout: archive # Or a specific layout for publications
      author_profile: true

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/abhatta1234
    icon: fab fa-github-square

# Mastodon instances
# mastodon:
# - username: "jekyll"
#   instance: "example.com"
# - username: "jekyll2"
#   instance: "example.com"

# Skin selection
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Optional features
search                   : false # true, false (default)
search_full_content      : false # true, false (default)
search_provider          : # "lunr", "google", "custom" (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false

# Hire me button
# hire_me_button: true

# Lazy Loading
# lazy_load_images: true

# Table of contents
# toc_levels: 1..6

#lunr
# lunr:
#  stopwords: # /assets/js/lunr/stopwords_en.js # true, false (default)
#  tokenizer_separator: /[\s\-/]+/ # /[\s\-/]+/ (default)

# Localization
# translations:
#  button:
#    follow: "Follow"
#    preview: "Preview"
#    edit: "Edit on GitHub"
#    buy: "Buy for $ VERSION"
#    share: "Share"
#    read_more: "Read More"

#lunr
lunr:
 stopwords: /assets/js/lunr/stopwords_en.js
 tokenizer_separator: /[\s\-/]+/
